version: '3.8'

services:
  backend:
    build: ./backend
    container_name: dog_backend
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/results:/app/results
      - ./backend/heart_segmentation.db:/app/heart_segmentation.db
    restart: unless-stopped
    # Removed ports mapping so it doesn't conflict with other backends on the VPS

  frontend:
    build: ./frontend
    container_name: dog_frontend
    depends_on:
      - backend
    ports:
      - "3000:80" # Maps port 3000 of Hostinger VPS to port 80 of Nginx
    restart: unless-stopped
